import { HiOutlineClipboardCopy, HiOutlineDownload } from 'react-icons/hi';
import toast from 'react-hot-toast';

export default function ResearchCard({ research }) {
  if (!research) return null;

  const copyToClipboard = (text, label) => {
    navigator.clipboard.writeText(text);
    toast.success(`${label} copied to clipboard!`);
  };

  const downloadAsMarkdown = () => {
    const content = `# Research: ${research.company_name}

## Summary
${research.summary}

## Pain Points
${research.pain_points.map((p) => `- ${p}`).join('\n')}

## Outreach Email
${research.generated_pitch}

---
*Generated by AgentScout on ${new Date(research.timestamp).toLocaleDateString()}*
`;
    const blob = new Blob([content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${research.company_name || 'research'}-outreach.md`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Downloaded as Markdown!');
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold text-white">
            {research.company_name}
          </h2>
          <p className="text-sm text-gray-500 mt-1">
            {research.target_url}
          </p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={downloadAsMarkdown}
            className="flex items-center gap-2 px-4 py-2 rounded-lg bg-white/5 border border-white/10 
              text-gray-300 hover:text-white hover:bg-white/10 transition-all text-sm"
          >
            <HiOutlineDownload />
            Export MD
          </button>
        </div>
      </div>

      {/* Summary Card */}
      <div className="glass-card p-6">
        <div className="flex items-center justify-between mb-3">
          <h3 className="text-lg font-semibold text-primary-400">Summary</h3>
          <button
            onClick={() => copyToClipboard(research.summary, 'Summary')}
            className="text-gray-500 hover:text-primary-400 transition-colors"
          >
            <HiOutlineClipboardCopy className="text-lg" />
          </button>
        </div>
        <p className="text-gray-300 leading-relaxed">{research.summary}</p>
      </div>

      {/* Pain Points Card */}
      <div className="glass-card p-6">
        <div className="flex items-center justify-between mb-3">
          <h3 className="text-lg font-semibold text-primary-400">Pain Points</h3>
          <button
            onClick={() =>
              copyToClipboard(research.pain_points.join('\n'), 'Pain Points')
            }
            className="text-gray-500 hover:text-primary-400 transition-colors"
          >
            <HiOutlineClipboardCopy className="text-lg" />
          </button>
        </div>
        <ul className="space-y-3">
          {research.pain_points.map((point, i) => (
            <li key={i} className="flex items-start gap-3">
              <span className="flex-shrink-0 w-6 h-6 rounded-full bg-primary-600/20 text-primary-400 text-xs flex items-center justify-center font-bold mt-0.5">
                {i + 1}
              </span>
              <span className="text-gray-300">{point}</span>
            </li>
          ))}
        </ul>
      </div>

      {/* Generated Pitch Card */}
      <div className="glass-card p-6">
        <div className="flex items-center justify-between mb-3">
          <h3 className="text-lg font-semibold text-primary-400">
            Outreach Email Draft
          </h3>
          <button
            onClick={() =>
              copyToClipboard(research.generated_pitch, 'Email')
            }
            className="flex items-center gap-1 text-sm text-gray-500 hover:text-primary-400 transition-colors"
          >
            <HiOutlineClipboardCopy />
            Copy Email
          </button>
        </div>
        <div className="bg-dark-900/50 rounded-xl p-5 border border-white/5">
          <pre className="text-gray-300 leading-relaxed whitespace-pre-wrap font-sans text-sm">
            {research.generated_pitch}
          </pre>
        </div>
      </div>
    </div>
  );
}
